// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CandidatesVslanguages
    {
        public int CandidateId { get; set; }
        public int LanguagesId { get; set; }
    }
}