// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class VAllCandidates
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BeginYear { get; set; }
        public DateTime LastUpdateDate { get; set; }
        public string LangIds { get; set; }
        public string LangNames { get; set; }
    }
}